name: CI/CD

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  generate-models:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: sudo apt install -y zip

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Train models
        run: python3 scripts/03-train.py

      - name: Compress models
        run: zip -r data/output/models.zip data/output
      
      - name: Upload models
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: data/output/models.zip
          asset_name: models.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "This release has been automatically generated by a workflow."